
export const metadata = {
  title: 'Images - SnapStock',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
        {children}
    </>
  )
}
